/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiReverseSearchRouteImport } from './routes/api/reverse-search'
import { Route as CreatorIdRouteImport } from './routes/creator.$id'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as WorkSourceIdRouteImport } from './routes/work.$source.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReverseSearchRoute = ApiReverseSearchRouteImport.update({
  id: '/api/reverse-search',
  path: '/api/reverse-search',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIdRoute = CreatorIdRouteImport.update({
  id: '/creator/$id',
  path: '/creator/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSourceIdRoute = WorkSourceIdRouteImport.update({
  id: '/work/$source/$id',
  path: '/work/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
  '/api/media': typeof ApiMediaRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/reverse-search': typeof ApiReverseSearchRoute
  '/creator/$id': typeof CreatorIdRoute
  '/user/$id': typeof UserIdRoute
  '/work/$source/$id': typeof WorkSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
  '/api/media': typeof ApiMediaRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/reverse-search': typeof ApiReverseSearchRoute
  '/creator/$id': typeof CreatorIdRoute
  '/user/$id': typeof UserIdRoute
  '/work/$source/$id': typeof WorkSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
  '/api/media': typeof ApiMediaRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/reverse-search': typeof ApiReverseSearchRoute
  '/creator/$id': typeof CreatorIdRoute
  '/user/$id': typeof UserIdRoute
  '/work/$source/$id': typeof WorkSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/queue'
    | '/search'
    | '/settings'
    | '/vault'
    | '/api/media'
    | '/api/proxy'
    | '/api/reverse-search'
    | '/creator/$id'
    | '/user/$id'
    | '/work/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queue'
    | '/search'
    | '/settings'
    | '/vault'
    | '/api/media'
    | '/api/proxy'
    | '/api/reverse-search'
    | '/creator/$id'
    | '/user/$id'
    | '/work/$source/$id'
  id:
    | '__root__'
    | '/'
    | '/queue'
    | '/search'
    | '/settings'
    | '/vault'
    | '/api/media'
    | '/api/proxy'
    | '/api/reverse-search'
    | '/creator/$id'
    | '/user/$id'
    | '/work/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueueRoute: typeof QueueRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  VaultRoute: typeof VaultRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ApiReverseSearchRoute: typeof ApiReverseSearchRoute
  CreatorIdRoute: typeof CreatorIdRoute
  UserIdRoute: typeof UserIdRoute
  WorkSourceIdRoute: typeof WorkSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reverse-search': {
      id: '/api/reverse-search'
      path: '/api/reverse-search'
      fullPath: '/api/reverse-search'
      preLoaderRoute: typeof ApiReverseSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$id': {
      id: '/creator/$id'
      path: '/creator/$id'
      fullPath: '/creator/$id'
      preLoaderRoute: typeof CreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$source/$id': {
      id: '/work/$source/$id'
      path: '/work/$source/$id'
      fullPath: '/work/$source/$id'
      preLoaderRoute: typeof WorkSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueueRoute: QueueRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  VaultRoute: VaultRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiProxyRoute: ApiProxyRoute,
  ApiReverseSearchRoute: ApiReverseSearchRoute,
  CreatorIdRoute: CreatorIdRoute,
  UserIdRoute: UserIdRoute,
  WorkSourceIdRoute: WorkSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
